/*
 * Watchman API
 *
 * Moov Watchman is an HTTP API and Go library to download, parse and offer search functions over numerous trade sanction lists from the United States, European Union governments, agencies, and non profits for complying with regional laws. Also included is a web UI and async webhook notification service to initiate processes on remote systems.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// OfacType Used for classifying SDNs or SSI identities — typically represents an individual or company
type OfacType string

// List of OfacType
const (
	OFACTYPE_INDIVIDUAL OfacType = "individual"
	OFACTYPE_ENTITY     OfacType = "entity"
	OFACTYPE_VESSEL     OfacType = "vessel"
	OFACTYPE_AIRCRAFT   OfacType = "aircraft"
)
