/*
 * OFAC API
 *
 * OFAC (Office of Foreign Assets Control) API is designed to facilitate the enforcement of US government economic sanctions programs required by federal law. This project implements a modern REST HTTP API for companies and organizations to obey federal law and use OFAC data in their applications.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// OfacCustomer OFAC Customer and metadata
type OfacCustomer struct {
	// OFAC Customer ID
	ID        string             `json:"ID,omitempty"`
	Sdn       Sdn                `json:"sdn,omitempty"`
	Addresses []EntityAddress    `json:"addresses,omitempty"`
	Alts      []Alt              `json:"alts,omitempty"`
	Status    OfacCustomerStatus `json:"status,omitempty"`
}
