/*
 * OFAC API
 *
 * OFAC (Office of Foreign Assets Control) API is designed to facilitate the enforcement of US government economic sanctions programs required by federal law. This project implements a modern REST HTTP API for companies and organizations to obey federal law and use OFAC data in their applications.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// BIS Denied Persons List item
type Dpl struct {
	// Name of the Denied Person
	Name string `json:"name,omitempty"`
	// Denied Person's street address
	StreetAddress string `json:"streetAddress,omitempty"`
	// Denied Person's city
	City string `json:"city,omitempty"`
	// Denied Person's state
	State string `json:"state,omitempty"`
	// Denied Person's country
	Country string `json:"country,omitempty"`
	// Denied Person's postal code
	PostalCode string `json:"postalCode,omitempty"`
	// Date when denial came into effect
	EffectiveDate string `json:"effectiveDate,omitempty"`
	// Date when denial expires, if blank denial never expires
	ExpirationDate string `json:"expirationDate,omitempty"`
	// Denotes whether or not the Denied Person was added by a standard order
	StandardOrder string `json:"standardOrder,omitempty"`
	// Most recent date when the Denied Person record was updated
	LastUpdate string `json:"lastUpdate,omitempty"`
	// Most recent action taken regarding the denial
	Action string `json:"action,omitempty"`
	// Reference to the order's citation in the Federal Register
	FrCitation string  `json:"frCitation,omitempty"`
	Match      float32 `json:"match,omitempty"`
}
