/*
 * Watchman API
 *
 * Moov Watchman is an HTTP API and Go library to download, parse and offer search functions over numerous trade sanction lists from the United States, European Union governments, agencies, and non profits for complying with regional laws. Also included is a web UI and async webhook notification service to initiate processes on remote systems.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// UpdateOfacCompanyStatus Request body to update a company status.
type UpdateOfacCompanyStatus struct {
	// manual override of company/SDN sanction status
	Status string `json:"status"`
	// Free form notes about manually changing the Company status
	Notes string `json:"notes,omitempty"`
}
