/*
 * Watchman API
 *
 * Moov Watchman offers download, parse, and search functions over numerous U.S. trade sanction lists for complying with regional laws. Also included is a web UI and async webhook notification service to initiate processes on remote systems.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// Unverified struct for Unverified
type Unverified struct {
	EntityID      string   `json:"entityID,omitempty"`
	Name          string   `json:"name,omitempty"`
	Addresses     []string `json:"addresses,omitempty"`
	SourceListURL string   `json:"sourceListURL,omitempty"`
	SourceInfoURL string   `json:"sourceInfoURL,omitempty"`
	// Match percentage of search query
	Match float32 `json:"match,omitempty"`
	// The highest scoring term from the search query. This term is the precomputed indexed value used by the search algorithm.
	MatchedName string `json:"matchedName,omitempty"`
}
