/*
 * Watchman API
 *
 * Moov Watchman offers download, parse, and search functions over numerous U.S. trade sanction lists for complying with regional laws. Also included is a web UI and async webhook notification service to initiate processes on remote systems.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// EuConsolidatedSanctionsList struct for EuConsolidatedSanctionsList
type EuConsolidatedSanctionsList struct {
	FileGenerationDate         string                 `json:"fileGenerationDate,omitempty"`
	EntityLogicalId            int32                  `json:"entityLogicalId,omitempty"`
	EntityRemark               string                 `json:"entityRemark,omitempty"`
	EntitySubjectType          string                 `json:"entitySubjectType,omitempty"`
	EntityPublicationURL       string                 `json:"entityPublicationURL,omitempty"`
	EntityReferenceNumber      string                 `json:"entityReferenceNumber,omitempty"`
	NameAliasWholeNames        []string               `json:"nameAliasWholeNames,omitempty"`
	NameAliasTitles            []string               `json:"nameAliasTitles,omitempty"`
	AddressCities              []string               `json:"addressCities,omitempty"`
	AddressStreets             []string               `json:"addressStreets,omitempty"`
	AddressPoBoxes             []string               `json:"addressPoBoxes,omitempty"`
	AddressZipCodes            []string               `json:"addressZipCodes,omitempty"`
	AddressCountryDescriptions []string               `json:"addressCountryDescriptions,omitempty"`
	BirthDates                 []string               `json:"birthDates,omitempty"`
	BirthCities                []string               `json:"birthCities,omitempty"`
	BirthCountries             []string               `json:"birthCountries,omitempty"`
	ValidFromTo                map[string]interface{} `json:"validFromTo,omitempty"`
	// Match percentage of search query
	Match float32 `json:"match,omitempty"`
	// The highest scoring term from the search query. This term is the precomputed indexed value used by the search algorithm.
	MatchedName string `json:"matchedName,omitempty"`
}
