/*
 * Watchman API
 *
 * Moov Watchman is an HTTP API and Go library to download, parse and offer search functions over numerous trade sanction lists from the United States, European Union governments, agencies, and non profits for complying with regional laws. Also included is a web UI and async webhook notification service to initiate processes on remote systems.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// OfacAlt Alternate name from OFAC list
type OfacAlt struct {
	EntityID         string  `json:"entityID,omitempty"`
	AlternateID      string  `json:"alternateID,omitempty"`
	AlternateType    string  `json:"alternateType,omitempty"`
	AlternateName    string  `json:"alternateName,omitempty"`
	AlternateRemarks string  `json:"alternateRemarks,omitempty"`
	Match            float32 `json:"match,omitempty"`
}
