/*
 * OFAC API
 *
 * OFAC (Office of Foreign Assets Control) API is designed to facilitate the enforcement of US government economic sanctions programs required by federal law. This project implements a modern REST HTTP API for companies and organizations to obey federal law and use OFAC data in their applications.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Alternate name from OFAC list
type Alt struct {
	EntityID      string `json:"EntityID,omitempty"`
	AlternateID   string `json:"AlternateID,omitempty"`
	AlternateType string `json:"AlternateType,omitempty"`
	AlternateName string `json:"AlternateName,omitempty"`
}
