/*
 * Watchman API
 *
 * Moov Watchman offers download, parse, and search functions over numerous U.S. trade sanction lists for complying with regional laws. Also included is a web UI and async webhook notification service to initiate processes on remote systems.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// UpdateOfacCustomerStatus Request body to update a customers status.
type UpdateOfacCustomerStatus struct {
	// Manual override of customer/SDN sanction status
	Status string `json:"status"`
	// Free form notes about manually changing the Customer status
	Notes string `json:"notes,omitempty"`
}
