/*
 * Watchman API
 *
 * Moov Watchman offers download, parse, and search functions over numerous U.S. trade sanction lists for complying with regional laws. Also included is a web UI and async webhook notification service to initiate processes on remote systems.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// SdnType Used for classifying SDNs — typically represents an individual or company
type SdnType string

// List of SdnType
const (
	SDNTYPE_INDIVIDUAL SdnType = "individual"
	SDNTYPE_ENTITY     SdnType = "entity"
	SDNTYPE_VESSEL     SdnType = "vessel"
	SDNTYPE_AIRCRAFT   SdnType = "aircraft"
)
