/*
 * OFAC API
 *
 * OFAC (Office of Foreign Assets Control) API is designed to facilitate the enforcement of US government economic sanctions programs required by federal law. This project implements a modern REST HTTP API for companies and organizations to obey federal law and use OFAC data in their applications.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// Status properties of an OFAC Company
type OfacCompanyStatus struct {
	// User ID provided when updating status
	UserID string `json:"userID,omitempty"`
	// Optional note from updating status
	Note string `json:"note,omitempty"`
	// Manually applied status for OFAC Company
	Status    string    `json:"status,omitempty"`
	CreatedAt time.Time `json:"createdAt,omitempty"`
}
