/*
 * Watchman API
 *
 * Moov Watchman offers download, parse, and search functions over numerous U.S. trade sanction lists for complying with regional laws. Also included is a web UI and async webhook notification service to initiate processes on remote systems.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// PalestinianLegislativeCouncil struct for PalestinianLegislativeCouncil
type PalestinianLegislativeCouncil struct {
	EntityID       string   `json:"entityID,omitempty"`
	EntityNumber   string   `json:"entityNumber,omitempty"`
	Type           string   `json:"type,omitempty"`
	Programs       []string `json:"programs,omitempty"`
	Name           string   `json:"name,omitempty"`
	Addresses      []string `json:"addresses,omitempty"`
	Remarks        string   `json:"remarks,omitempty"`
	SourceListURL  string   `json:"sourceListURL,omitempty"`
	AlternateNames []string `json:"alternateNames,omitempty"`
	DatesOfBirth   string   `json:"datesOfBirth,omitempty"`
	PlacesOfBirth  string   `json:"placesOfBirth,omitempty"`
	SourceInfoURL  string   `json:"sourceInfoURL,omitempty"`
	// Match percentage of search query
	Match float32 `json:"match,omitempty"`
}
