/*
 * Watchman API
 *
 * Moov Watchman offers download, parse, and search functions over numerous U.S. trade sanction lists for complying with regional laws. Also included is a web UI and async webhook notification service to initiate processes on remote systems.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// OfacWatchRequest Webhook or other means of notification on search criteria. OFAC will make a POST request with a body of the customer or company (SDN, AltNames, and Address).
type OfacWatchRequest struct {
	// Private token supplied by clients to be used for authenticating webhooks.
	AuthToken string `json:"authToken"`
	// HTTPS url for webhook on search match
	Webhook string `json:"webhook"`
}
