/*
 * Watchman API
 *
 * Moov Watchman offers download, parse, and search functions over numerous U.S. trade sanction lists for complying with regional laws. Also included is a web UI and async webhook notification service to initiate processes on remote systems.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// OfacEntityAddress Physical address from OFAC list
type OfacEntityAddress struct {
	EntityID                    string `json:"entityID,omitempty"`
	AddressID                   string `json:"addressID,omitempty"`
	Address                     string `json:"address,omitempty"`
	CityStateProvincePostalCode string `json:"cityStateProvincePostalCode,omitempty"`
	Country                     string `json:"country,omitempty"`
	// Match percentage of search query
	Match float32 `json:"match,omitempty"`
}
