/*
 * Watchman API
 *
 * Moov Watchman offers download, parse, and search functions over numerous U.S. trade sanction lists for complying with regional laws. Also included is a web UI and async webhook notification service to initiate processes on remote systems.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// OfacSdn Specially designated national from OFAC list
type OfacSdn struct {
	EntityID string  `json:"entityID,omitempty"`
	SdnName  string  `json:"sdnName,omitempty"`
	SdnType  SdnType `json:"sdnType,omitempty"`
	// Programs is the sanction programs this SDN was added from
	Programs []string `json:"programs,omitempty"`
	Title    string   `json:"title,omitempty"`
	// Remarks on SDN and often additional information about the SDN
	Remarks string `json:"remarks,omitempty"`
	// Match percentage of search query
	Match float32 `json:"match,omitempty"`
}
