/*
 * Watchman API
 *
 * Moov Watchman offers download, parse, and search functions over numerous U.S. trade sanction lists for complying with regional laws. Also included is a web UI and async webhook notification service to initiate processes on remote systems.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// OfacWatch Customer or Company watch
type OfacWatch struct {
	// Object representing a customer or company watch
	WatchID string `json:"watchID,omitempty"`
}
