/*
 * OFAC API
 *
 * OFAC (Office of Foreign Assets Control) API is designed to facilitate the enforcement of US government economic sanctions programs required by federal law. This project implements a modern REST HTTP API for companies and organizations to obey federal law and use OFAC data in their applications.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Search results containing SDNs, alternate names and/or addreses
type Search struct {
	SDNs      []Sdn     `json:"SDNs,omitempty"`
	AltNames  []Alt     `json:"altNames,omitempty"`
	Addresses []Address `json:"addresses,omitempty"`
}
