/*
 * Watchman API
 *
 * Moov Watchman is an HTTP API and Go library to download, parse and offer search functions over numerous trade sanction lists from the United States, European Union governments, agencies, and non profits for complying with regional laws. Also included is a web UI and async webhook notification service to initiate processes on remote systems.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// OfacEntityAddress Physical address from OFAC list
type OfacEntityAddress struct {
	EntityID                    string  `json:"entityID,omitempty"`
	AddressID                   string  `json:"addressID,omitempty"`
	Address                     string  `json:"address,omitempty"`
	CityStateProvincePostalCode string  `json:"cityStateProvincePostalCode,omitempty"`
	Country                     string  `json:"country,omitempty"`
	Match                       float32 `json:"match,omitempty"`
}
