/*
 * OFAC API
 *
 * OFAC (Office of Foreign Assets Control) API is designed to facilitate the enforcement of US government economic sanctions programs required by federal law. This project implements a modern REST HTTP API for companies and organizations to obey federal law and use OFAC data in their applications.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Alternate name from OFAC list
type Alt struct {
	EntityID         string  `json:"entityID,omitempty"`
	AlternateID      string  `json:"alternateID,omitempty"`
	AlternateType    string  `json:"alternateType,omitempty"`
	AlternateName    string  `json:"alternateName,omitempty"`
	AlternateRemarks string  `json:"alternateRemarks,omitempty"`
	Match            float32 `json:"match,omitempty"`
}
