/*
 * Watchman API
 *
 * Moov Watchman offers download, parse, and search functions over numerous U.S. trade sanction lists for complying with regional laws. Also included is a web UI and async webhook notification service to initiate processes on remote systems.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// OfacCustomer OFAC Customer and metadata
type OfacCustomer struct {
	// OFAC Customer ID
	ID        string              `json:"ID,omitempty"`
	Sdn       OfacSdn             `json:"sdn,omitempty"`
	Addresses []OfacEntityAddress `json:"addresses,omitempty"`
	Alts      []OfacAlt           `json:"alts,omitempty"`
	Status    OfacCustomerStatus  `json:"status,omitempty"`
}
