/*
 * OFAC API
 *
 * OFAC (Office of Foreign Assets Control) API is designed to facilitate the enforcement of US government economic sanctions programs required by federal law. This project implements a modern REST HTTP API for companies and organizations to obey federal law and use OFAC data in their applications.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Request body to update a customers status.
type UpdateCustomerStatus struct {
	// manual override of customer/SDN sanction status
	Status string `json:"status"`
	// Free form notes about manually changing the Customer status
	Notes string `json:"notes,omitempty"`
}
