/*
 * Watchman API
 *
 * Moov Watchman offers download, parse, and search functions over numerous U.S. trade sanction lists for complying with regional laws. Also included is a web UI and async webhook notification service to initiate processes on remote systems.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

import (
	"time"
)

// OfacCustomerStatus Status properties of an OFAC Customer
type OfacCustomerStatus struct {
	// User ID provided when updating status
	UserID string `json:"userID,omitempty"`
	// Optional note from updating status
	Note string `json:"note,omitempty"`
	// Manually applied status for OFAC Customer
	Status    string    `json:"status,omitempty"`
	CreatedAt time.Time `json:"createdAt,omitempty"`
}
