# Stage 1: Install dependencies with root privileges
FROM registry.access.redhat.com/ubi9/go-toolset as builder-deps
USER root
RUN dnf install -y --allowerasing --setopt=tsflags=nodocs \
    curl \
    autoconf \
    automake \
    libtool \
    pkgconfig \
    && dnf clean all

# Stage 2: Build the application
FROM registry.access.redhat.com/ubi9/go-toolset as builder
ARG VERSION
WORKDIR /opt/app-root/src/
COPY --from=builder-deps /usr /usr
COPY . .
RUN go mod download
RUN make install
RUN VERSION=${VERSION} make build-server

# Stage 3: Frontend build
FROM node:21-bookworm as frontend
COPY webui/ /watchman/
WORKDIR /watchman/
RUN npm install --legacy-peer-deps
RUN npm run build

# Stage 4: Final stage
FROM registry.access.redhat.com/ubi9/ubi-minimal:9.5-1733767867
ARG VERSION=unknown
LABEL maintainer="Moov <oss@moov.io>"
LABEL name="watchman"
LABEL version=$VERSION
COPY --from=builder /opt/app-root/src/bin/server /bin/server
COPY --from=frontend /watchman/build/ /watchman/
ENV WEB_ROOT=/watchman/
ENTRYPOINT ["/bin/server"]
