version: '3'

services:

  # Containers used for testing
  mysql:
    image: mysql:9.5.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=watchman
      - MYSQL_USER=watchman
      - MYSQL_PASSWORD=watchman
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - intranet
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    tmpfs: # Run this mysql in memory as its used for testing
      - /var/lib/mysql

  postgres:
    image: postgres:18
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=watchman
      - POSTGRES_USER=watchman
      - POSTGRES_PASSWORD=watchman
    networks:
    - intranet

networks:
  intranet: {}
