package algmatrix

import (
	"bytes"
	"encoding/csv"
	"fmt"
	"strings"

	"github.com/moov-io/watchman/internal/stringscore"
	"github.com/moov-io/watchman/internal/tfidf"
)

type pair struct {
	query, index, note string
}

var pairs = []pair{
	{"precede", "preceed", "spelling / doubled letter"}, //nolint:misspell
	{"achieve", "acheive", "transposition"},             //nolint:misspell
	{"smith", "smythe", "phonetic (English)"},
	{"catherine", "katherine", "C/K onset"},
	{"qaddafi", "gaddafi", "Q/G onset"},
	{"aleksandr", "alexander", "transliteration"},
	{"nicolas maduro", "nicolas moros maduro", "missing middle"},
	{"alexander lukashenko", "lukashenko alexander grigoryevich", "token order / extra given"},
	{"saddam hussein", "saddam hussein al tikriti", "missing suffix"},
	{"hadi", "hadi alwai", "short vs longer"},
	{"li shangfu", "li shanlan", "shared short token"},
	{"vladimir", "vladimirov vladimir vladimirovich", "doubled family"},
	{"dominguez", "jimenez", "false-positive control"},
	{"cycloserine", "cyclosporine", "LASA look-alike"},
	{"schumacher", "shumaker", "German / English spelling"},
}

type column struct {
	key   string
	hdr   string
	cfg   stringscore.ScoringConfig
	tfidf bool
}

func columns() []column {
	jw := stringscore.ScoringConfig{}
	return []column{
		{key: "jw", hdr: "jw", cfg: jw},
		{key: "jw-tfidf", hdr: "jw+tfidf", cfg: jw, tfidf: true},
		{key: "soundex", hdr: "soundex", cfg: stringscore.ScoringConfig{UseSoundexBoost: true, SoundexBoostWeight: 0.12}},
		{key: "dmeta", hdr: "dmeta", cfg: stringscore.ScoringConfig{UseDoubleMetaphoneBoost: true, SoundexBoostWeight: 0.12}},
		{key: "bmpm", hdr: "bmpm", cfg: stringscore.ScoringConfig{UseBeiderMorseBoost: true, SoundexBoostWeight: 0.12}},
		{key: "bidist", hdr: "bidist", cfg: stringscore.ScoringConfig{TokenScorer: stringscore.TokenScorerSoftBidist}},
		{key: "bidist-tfidf", hdr: "bidist+tfidf", cfg: stringscore.ScoringConfig{TokenScorer: stringscore.TokenScorerSoftBidist}, tfidf: true},
		{key: "bisim", hdr: "bisim", cfg: stringscore.ScoringConfig{TokenScorer: stringscore.TokenScorerSoftBisim}},
		{key: "editex", hdr: "editex", cfg: stringscore.ScoringConfig{TokenScorer: stringscore.TokenScorerEditex}},
		{key: "editex-tfidf", hdr: "editex+tfidf", cfg: stringscore.ScoringConfig{TokenScorer: stringscore.TokenScorerEditex}, tfidf: true},
		{key: "nsim", hdr: "nsim", cfg: stringscore.ScoringConfig{TokenScorer: stringscore.TokenScorerNSim}},
		{key: "nsim3", hdr: "nsim-3", cfg: stringscore.ScoringConfig{TokenScorer: stringscore.TokenScorerNSim3}},
	}
}

type scoredRow struct {
	pair
	scores []float64
}

func compute() ([]column, []scoredRow) {
	idx := buildIndex()
	cols := columns()
	rows := make([]scoredRow, 0, len(pairs))
	for _, p := range pairs {
		q := strings.Fields(p.query)
		ix := strings.Fields(p.index)
		scores := make([]float64, len(cols))
		for i, c := range cols {
			var tf *tfidf.Index
			if c.tfidf {
				tf = idx
			}
			scores[i] = score(q, ix, c.cfg, tf)
		}
		rows = append(rows, scoredRow{pair: p, scores: scores})
	}
	return cols, rows
}

// Render returns the Jekyll markdown page.
func Render() string {
	cols, rows := compute()

	var b strings.Builder
	b.WriteString(`---
layout: page
title: Algorithm comparison
hide_hero: true
show_sidebar: false
menubar: docs-menu
---

# Algorithm comparison

Generated by ` + "`go test ./internal/algmatrix`" + ` (markdown and [CSV]({{ '/algorithm-comparison.csv' | relative_url }})). Scores are Watchman **BestPairs** on already-lowercased tokens, with the production first-letter phonetic filter **on**. TF-IDF columns use a tiny index built from these rows (not the full SDN list). Boost algorithms keep Jaro-Winkler as the inner metric.

| Abbrev | ` + "`?algorithm=`" + ` | What changes |
|--------|-----------------|--------------|
| jw | ` + "`jaro-winkler`" + ` (default) | Inner scorer: Jaro-Winkler |
| soundex | ` + "`soundex`" + ` | JW + 12% boost if Soundex codes match |
| dmeta | ` + "`double-metaphone`" + ` | JW + 12% boost if Double Metaphone codes overlap |
| bmpm | ` + "`beider-morse`" + ` | JW + 12% boost if generic Beider-Morse keys overlap |
| bidist | ` + "`soft-bidist`" + ` | Inner scorer: Soft-Bidist |
| bisim | ` + "`soft-bisim`" + ` | Inner scorer: Soft-Bisim |
| editex | ` + "`editex`" + ` | Inner scorer: Editex |
| nsim | ` + "`nsim`" + ` | Inner scorer: Kondrak N-SIM n=2 |
| nsim-3 | ` + "`nsim-3`" + ` | Inner scorer: Kondrak N-SIM n=3 |
| +tfidf | same algorithm | BestPairs weighted by TF-IDF on this table's names |

Length-difference and different-first-letter penalties still apply. ` + "`dominguez`/`jimenez`" + ` is the false-positive control (first-letter filter).

<p><a class="button is-link is-light" href="{{ '/algorithm-comparison.csv' | relative_url }}" download="watchman-algorithm-comparison.csv">Download CSV</a></p>

<div class="notification is-info is-light">
<p><strong>Tip:</strong> Use <a href="https://github.com/adamdecaf/csvq">csvq</a> to sort the downloaded CSV by algorithm.</p>
<pre><code>csvq -sort.dsc bmpm -format table -headers ~/Downloads/watchman-algorithm-comparison.csv</code></pre>
</div>

<style>
.alg-matrix { overflow-x: auto; max-width: 100%; }
.alg-matrix table { white-space: nowrap; }
</style>

<div class="table-container alg-matrix" markdown="1">

`)

	b.WriteString("| query | index | note |")
	for _, c := range cols {
		b.WriteString(" ")
		b.WriteString(c.hdr)
		b.WriteString(" |")
	}
	b.WriteString("\n|---|---|---|")
	for range cols {
		b.WriteString("---:|")
	}
	b.WriteString("\n")

	for _, row := range rows {
		b.WriteString("| `")
		b.WriteString(row.query)
		b.WriteString("` | `")
		b.WriteString(row.index)
		b.WriteString("` | ")
		b.WriteString(row.note)
		b.WriteString(" |")
		for _, s := range row.scores {
			b.WriteString(fmt.Sprintf(" %.3f |", s))
		}
		b.WriteString("\n")
	}
	b.WriteString("\n</div>\n")
	return b.String()
}

// RenderCSV returns the same scores as Render, as CSV (header + one row per pair).
func RenderCSV() string {
	cols, rows := compute()
	var buf bytes.Buffer
	w := csv.NewWriter(&buf)
	header := []string{"query", "index", "note"}
	for _, c := range cols {
		header = append(header, c.hdr)
	}
	_ = w.Write(header)
	for _, row := range rows {
		rec := []string{row.query, row.index, row.note}
		for _, s := range row.scores {
			rec = append(rec, fmt.Sprintf("%.3f", s))
		}
		_ = w.Write(rec)
	}
	w.Flush()
	return buf.String()
}

func score(q, idx []string, cfg stringscore.ScoringConfig, tf *tfidf.Index) float64 {
	if tf != nil && tf.Enabled() {
		qw := tf.GetWeights(q)
		iw := tf.GetWeights(idx)
		return stringscore.BestPairCombinationJaroWinklerWeightedWithConfig(q, idx, qw, iw, cfg)
	}
	return stringscore.BestPairCombinationJaroWinklerWithConfig(q, idx, cfg)
}

func buildIndex() *tfidf.Index {
	cfg := tfidf.DefaultConfig()
	cfg.Enabled = true
	idx := tfidf.NewIndex(cfg)
	var docs [][]string
	seen := map[string]bool{}
	for _, p := range pairs {
		for _, name := range []string{p.query, p.index} {
			if seen[name] {
				continue
			}
			seen[name] = true
			docs = append(docs, strings.Fields(name))
		}
	}
	idx.Build(docs)
	return idx
}
