package algmatrix

import (
	"fmt"
	"strings"

	"github.com/moov-io/watchman/internal/stringscore"
	"github.com/moov-io/watchman/internal/tfidf"
)

type pair struct {
	query, index, note string
}

var pairs = []pair{
	{"precede", "preceed", "spelling / doubled letter"},
	{"achieve", "acheive", "transposition"},
	{"smith", "smythe", "phonetic (English)"},
	{"catherine", "katherine", "C/K onset"},
	{"qaddafi", "gaddafi", "Q/G onset"},
	{"aleksandr", "alexander", "transliteration"},
	{"nicolas maduro", "nicolas moros maduro", "missing middle"},
	{"alexander lukashenko", "lukashenko alexander grigoryevich", "token order / extra given"},
	{"saddam hussein", "saddam hussein al tikriti", "missing suffix"},
	{"hadi", "hadi alwai", "short vs longer"},
	{"li shangfu", "li shanlan", "shared short token"},
	{"vladimir", "vladimirov vladimir vladimirovich", "doubled family"},
	{"dominguez", "jimenez", "false-positive control"},
	{"cycloserine", "cyclosporine", "LASA look-alike"},
	{"schumacher", "shumaker", "German / English spelling"},
}

type column struct {
	key   string
	hdr   string
	cfg   stringscore.ScoringConfig
	tfidf bool
}

func columns() []column {
	jw := stringscore.ScoringConfig{}
	return []column{
		{key: "jw", hdr: "jw", cfg: jw},
		{key: "jw-tfidf", hdr: "jw+tfidf", cfg: jw, tfidf: true},
		{key: "soundex", hdr: "soundex", cfg: stringscore.ScoringConfig{UseSoundexBoost: true, SoundexBoostWeight: 0.12}},
		{key: "dmeta", hdr: "dmeta", cfg: stringscore.ScoringConfig{UseDoubleMetaphoneBoost: true, SoundexBoostWeight: 0.12}},
		{key: "bmpm", hdr: "bmpm", cfg: stringscore.ScoringConfig{UseBeiderMorseBoost: true, SoundexBoostWeight: 0.12}},
		{key: "bidist", hdr: "bidist", cfg: stringscore.ScoringConfig{TokenScorer: stringscore.TokenScorerSoftBidist}},
		{key: "bidist-tfidf", hdr: "bidist+tfidf", cfg: stringscore.ScoringConfig{TokenScorer: stringscore.TokenScorerSoftBidist}, tfidf: true},
		{key: "bisim", hdr: "bisim", cfg: stringscore.ScoringConfig{TokenScorer: stringscore.TokenScorerSoftBisim}},
		{key: "editex", hdr: "editex", cfg: stringscore.ScoringConfig{TokenScorer: stringscore.TokenScorerEditex}},
		{key: "editex-tfidf", hdr: "editex+tfidf", cfg: stringscore.ScoringConfig{TokenScorer: stringscore.TokenScorerEditex}, tfidf: true},
		{key: "nsim", hdr: "nsim", cfg: stringscore.ScoringConfig{TokenScorer: stringscore.TokenScorerNSim}},
		{key: "nsim3", hdr: "nsim-3", cfg: stringscore.ScoringConfig{TokenScorer: stringscore.TokenScorerNSim3}},
	}
}

// Render returns the Jekyll markdown page.
func Render() string {
	idx := buildIndex()
	cols := columns()

	var b strings.Builder
	b.WriteString(`---
layout: page
title: Algorithm comparison
hide_hero: true
show_sidebar: false
menubar: docs-menu
---

# Algorithm comparison

Generated by ` + "`go test ./internal/algmatrix`" + `. Scores are Watchman **BestPairs** on already-lowercased tokens, with the production first-letter phonetic filter **on**. TF-IDF columns use a tiny index built from these rows (not the full SDN list). Boost algorithms keep Jaro-Winkler as the inner metric.

| Abbrev | ` + "`?algorithm=`" + ` | What changes |
|--------|-----------------|--------------|
| jw | ` + "`jaro-winkler`" + ` (default) | Inner scorer: Jaro-Winkler |
| soundex | ` + "`soundex`" + ` | JW + 12% boost if Soundex codes match |
| dmeta | ` + "`double-metaphone`" + ` | JW + 12% boost if Double Metaphone codes overlap |
| bmpm | ` + "`beider-morse`" + ` | JW + 12% boost if generic Beider-Morse keys overlap |
| bidist | ` + "`soft-bidist`" + ` | Inner scorer: Soft-Bidist |
| bisim | ` + "`soft-bisim`" + ` | Inner scorer: Soft-Bisim |
| editex | ` + "`editex`" + ` | Inner scorer: Editex |
| nsim | ` + "`nsim`" + ` | Inner scorer: Kondrak N-SIM n=2 |
| nsim-3 | ` + "`nsim-3`" + ` | Inner scorer: Kondrak N-SIM n=3 |
| +tfidf | same algorithm | BestPairs weighted by TF-IDF on this table's names |

Length-difference and different-first-letter penalties still apply. ` + "`dominguez`/`jimenez`" + ` is the false-positive control (first-letter filter).

`)

	b.WriteString("| query | index | note |")
	for _, c := range cols {
		b.WriteString(" ")
		b.WriteString(c.hdr)
		b.WriteString(" |")
	}
	b.WriteString("\n|---|---|---|")
	for range cols {
		b.WriteString("---:|")
	}
	b.WriteString("\n")

	for _, p := range pairs {
		q := strings.Fields(p.query)
		ix := strings.Fields(p.index)
		b.WriteString("| `")
		b.WriteString(p.query)
		b.WriteString("` | `")
		b.WriteString(p.index)
		b.WriteString("` | ")
		b.WriteString(p.note)
		b.WriteString(" |")
		for _, c := range cols {
			var tf *tfidf.Index
			if c.tfidf {
				tf = idx
			}
			s := score(q, ix, c.cfg, tf)
			b.WriteString(fmt.Sprintf(" %.3f |", s))
		}
		b.WriteString("\n")
	}
	return b.String()
}

func score(q, idx []string, cfg stringscore.ScoringConfig, tf *tfidf.Index) float64 {
	if tf != nil && tf.Enabled() {
		qw := tf.GetWeights(q)
		iw := tf.GetWeights(idx)
		return stringscore.BestPairCombinationJaroWinklerWeightedWithConfig(q, idx, qw, iw, cfg)
	}
	return stringscore.BestPairCombinationJaroWinklerWithConfig(q, idx, cfg)
}

func buildIndex() *tfidf.Index {
	cfg := tfidf.DefaultConfig()
	cfg.Enabled = true
	idx := tfidf.NewIndex(cfg)
	var docs [][]string
	seen := map[string]bool{}
	for _, p := range pairs {
		for _, name := range []string{p.query, p.index} {
			if seen[name] {
				continue
			}
			seen[name] = true
			docs = append(docs, strings.Fields(name))
		}
	}
	idx.Build(docs)
	return idx
}
