//go:build ignore

// Command gen_union regenerates union_stopwords.go from the stopword lists shipped
// by github.com/bbalet/stopwords. The union lets RemoveStopwords skip language
// detection for tokens that no language could treat as a stopword.
//
// Run with: go generate ./internal/prepare/...
package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"golang.org/x/text/unicode/norm"
)

func main() {
	dir := goList("{{.Dir}}")
	version := goList("{{.Version}}")

	files, err := filepath.Glob(filepath.Join(dir, "stopwords_*.go"))
	if err != nil {
		fatal(err)
	}

	set := map[string]struct{}{}
	for _, file := range files {
		if strings.HasSuffix(file, "_test.go") {
			continue
		}
		collect(file, set)
	}
	if len(set) == 0 {
		fatal(fmt.Errorf("no stopwords found under %s", dir))
	}

	words := make([]string, 0, len(set))
	for w := range set {
		words = append(words, w)
	}
	sort.Strings(words)

	var b strings.Builder
	fmt.Fprint(&b, "// Code generated by gen_union.go; DO NOT EDIT.\n\n")
	fmt.Fprint(&b, "package prepare\n\n")
	fmt.Fprint(&b, "// bbaletStopwordsVersion is the github.com/bbalet/stopwords release this file\n")
	fmt.Fprint(&b, "// was generated from. TestStopwordUnionIsCurrent fails if the dependency is\n")
	fmt.Fprint(&b, "// upgraded without re-running go generate, so the union cannot silently drift.\n")
	fmt.Fprintf(&b, "const bbaletStopwordsVersion = %q\n\n", version)
	fmt.Fprint(&b, "// stopwordUnion is every stopword across all languages supported by\n")
	fmt.Fprint(&b, "// bbalet/stopwords, NFC-normalized and lowercased. If a token is not in this\n")
	fmt.Fprint(&b, "// set, no language's CleanString can remove it.\n")
	fmt.Fprintf(&b, "var stopwordUnion = func() map[string]struct{} {\n\tm := make(map[string]struct{}, %d)\n\tfor _, w := range stopwordUnionList {\n\t\tm[w] = struct{}{}\n\t}\n\treturn m\n}()\n\n", len(words))
	fmt.Fprint(&b, "var stopwordUnionList = []string{\n")
	for _, w := range words {
		fmt.Fprintf(&b, "\t%s,\n", strconv.Quote(w))
	}
	fmt.Fprint(&b, "}\n")

	if err := os.WriteFile("union_stopwords.go", []byte(b.String()), 0o644); err != nil {
		fatal(err)
	}
	fmt.Printf("union_stopwords.go: %d stopwords from bbalet/stopwords %s\n", len(words), version)
}

// collect adds the keys of every map[string]string literal in file to set. The
// bbalet stopword files declare each language as such a map with empty values.
func collect(file string, set map[string]struct{}) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, file, nil, 0)
	if err != nil {
		fatal(err)
	}
	ast.Inspect(f, func(n ast.Node) bool {
		kv, ok := n.(*ast.KeyValueExpr)
		if !ok {
			return true
		}
		key, ok := kv.Key.(*ast.BasicLit)
		if !ok || key.Kind != token.STRING {
			return true
		}
		if val, ok := kv.Value.(*ast.BasicLit); !ok || val.Kind != token.STRING {
			return true
		}
		word, err := strconv.Unquote(key.Value)
		if err != nil || word == "" {
			return true
		}
		set[strings.ToLower(norm.NFC.String(word))] = struct{}{}
		return true
	})
}

func goList(format string) string {
	out, err := exec.Command("go", "list", "-m", "-f", format, "github.com/bbalet/stopwords").Output()
	if err != nil {
		fatal(fmt.Errorf("go list stopwords: %w", err))
	}
	return strings.TrimSpace(string(out))
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "gen_union:", err)
	os.Exit(1)
}
