package model_validation

// Token-scorer comparison (Jaro-Winkler, Soundex, Soft-Bidist, Soft-Bisim, Editex,
// N-SIM, Double Metaphone, Beider-Morse, TF-IDF on/off) is generated by
// go test ./internal/algmatrix into docs/algorithm-comparison.md.
//
// TODO(adam): OFAC methodology matrix with preprocessing knobs
// (company name cleanup, stopword removal, i18n / utf-8 flattening).
