/*
 * Watchman Admin API
 *
 * Watchman is an HTTP API and Go library to download, parse and offer search functions over numerous trade sanction lists from the United States, European Union governments, agencies, and non profits for complying with regional laws. Also included is a web UI and async webhook notification service to initiate processes on remote systems.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin

// SdnType Used for classifying SDNs — typically represents an individual or company
type SdnType string

// List of SdnType
const (
	INDIVIDUAL SdnType = "individual"
	ENTITY     SdnType = "entity"
	VESSEL     SdnType = "vessel"
	AIRCRAFT   SdnType = "aircraft"
)
