/*
 * Watchman Admin API
 *
 * Watchman is an HTTP API and Go library to download, parse and offer search functions over numerous trade sanction lists from the United States, European Union governments, agencies, and non profits for complying with regional laws. Also included is a web UI and async webhook notification service to initiate processes on remote systems.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin

// OfacSdn Specially designated national from OFAC list
type OfacSdn struct {
	EntityID string  `json:"entityID,omitempty"`
	SdnName  string  `json:"sdnName,omitempty"`
	SdnType  SdnType `json:"sdnType,omitempty"`
	// Programs is the sanction programs this SDN was added from
	Programs []string `json:"programs,omitempty"`
	Title    string   `json:"title,omitempty"`
	Remarks  string   `json:"remarks,omitempty"`
	// Remarks on SDN and often additional information about the SDN
	Match float32 `json:"match,omitempty"`
}
