/*
 * Watchman Admin API
 *
 * Watchman is an HTTP API and Go library to download, parse and offer search functions over numerous trade sanction lists from the United States, European Union governments, agencies, and non profits for complying with regional laws. Also included is a web UI and async webhook notification service to initiate processes on remote systems.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin

// SdnDebugMetadata struct for SdnDebugMetadata
type SdnDebugMetadata struct {
	// Exact text stored in our index used for string ranking
	IndexedName string `json:"indexedName,omitempty"`
	// ID parsed from remarks field
	ParsedRemarksId string `json:"parsedRemarksId,omitempty"`
}
