/*
 * Watchman Admin API
 *
 * Watchman is an HTTP API and Go library to download, parse and offer search functions over numerous trade sanction lists from the United States, European Union governments, agencies, and non profits for complying with regional laws. Also included is a web UI and async webhook notification service to initiate processes on remote systems.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package admin

import (
	"time"
)

// DataRefresh struct for DataRefresh
type DataRefresh struct {
	// Count of OFAC SDNs after index
	SDNs int32 `json:"SDNs,omitempty"`
	// Count of OFAC alternate names after index
	AltNames int32 `json:"altNames,omitempty"`
	// Count of OFAC Addresses after index
	Addresses int32 `json:"addresses,omitempty"`
	// Count of SSI entities after index
	SectoralSanctions int32 `json:"sectoralSanctions,omitempty"`
	// Count of BSL denied persons after index
	DeniedPersons int32 `json:"deniedPersons,omitempty"`
	// Count of BIS entities after index
	BisEntities int32     `json:"bisEntities,omitempty"`
	Timestamp   time.Time `json:"timestamp,omitempty"`
}
